OMEGA_APIKEY: e9d50dcb5816ba14d40c7273abdf23822f38fe20
OMEGA_CELERY_CONFIG:
  BROKER_URL: amqp://GvwNjBk3kwdWRhAzgn9VT8tqJTPjAPDpzRBs:qzy7WmYGtaVhVusweEzhD2RdLtwuTTyTU8XS@hub.omegaml.io:5672/teT49kmM2V8Ua8fhXq8LAsWaUyJ7MmsS4A7h
  BROKER_USE_SSL: false
  CELERY_ACCEPT_CONTENT:
  - pickle
  - json
  CELERY_DEFAULT_QUEUE: default
  CELERY_RESULT_BACKEND: amqp
  CELERY_RESULT_SERIALIZER: pickle
  CELERY_SERIALIZER: pickle
  CELERY_TASK_RESULT_EXPIRES: 3600
  CELERY_TASK_SERIALIZER: pickle
OMEGA_FRAMEWORKS:
- scikit-learn
- tensorflow
- keras
- dash
OMEGA_MONGO_COLLECTION: omegaml
OMEGA_MONGO_URL: mongodb://3cv8atLy7vjygtUNT69vVZUPsac836yq238a:SSrUtARhbCGdxPpdwLn5Lypejj7WWULNnNQV@hub.omegaml.io:27017/RZdp6S3BBQ9AcmG8V9eWYxHnWxfKafNZGxgG
OMEGA_NOTEBOOK_COLLECTION: ipynb
OMEGA_RESTAPI_URL: https://hub.omegaml.io
OMEGA_TMP: /tmp
OMEGA_USERID: gazarias
